#!/usr/bin/env python3
import os
import pycparser
from pycparser.c_ast import NodeVisitor, Decl, PtrDecl, FuncDecl
from pycparser.c_generator import CGenerator

print("// Auto generated by gen_hooks.py")

SEEN = set()

class FunctionVisitor(NodeVisitor):
	def visit_Decl(self, node):
		if type(node.type) == FuncDecl:
			if node.name not in SEEN:
				SEEN.add(node.name)
				print(f"""	if (!YipReplaceFunction("{node.name}", {node.name}_old)) {{
		LogW("lua_upgrade: Failed to replace %s", "{node.name}");
	}}""")

print()
print("void lua_upgrade_hook51(void) {")

for filename in os.listdir():
	ast = pycparser.parse_file(
		filename,
		use_cpp=True,
		cpp_args=['-E', '-I/home/knot/Development/Hack/fake_libc_include']
	)
	
	FunctionVisitor().visit(ast)

print("}")
