#!/usr/bin/env python3
import os
import pycparser
from pycparser.c_ast import NodeVisitor, Decl, PtrDecl, FuncDecl
from pycparser.c_generator import CGenerator

print("// Loader for the upgraded version of Lua")
print("// Auto generated by gen_loader.py")

FUNCTION_NAMES = set()

class FunctionVisitor(NodeVisitor):
	def visit_Decl(self, node):
		if type(node.type) == FuncDecl:
			FUNCTION_NAMES.add(node.name)
			if type(node.type.type) == PtrDecl:
				node.type.type.type.declname += "_new"
			else:
				node.type.type.declname += "_new"
			decl = Decl(node.name + "_new", [], [], [], [], PtrDecl([], node.type), None, None)
			print(CGenerator().visit(decl) + ";")

# this happens i guess!
for filename in os.listdir():
	ast = pycparser.parse_file(
		filename,
		use_cpp=True,
		cpp_args=['-E', '-I/home/knot/Development/Hack/fake_libc_include']
	)
	
	FunctionVisitor().visit(ast)

print()
print("void lua_upgrade_load52(void) {")

for funcname in sorted(FUNCTION_NAMES):
	print(f'	{funcname}_new = dlsym(liblua, "{funcname}");')

print("}")
