#!/usr/bin/env python3
import os
import pycparser
from pycparser.c_ast import NodeVisitor, Decl, PtrDecl, FuncDecl, EllipsisParam
from pycparser.c_generator import CGenerator

SEEN = set()

print("// Auto generated by gen_shims.py")

def printcall(node):
	for arg in node.type.args:
		if type(arg) == EllipsisParam:
			print("	// WARNING: Call has ellipsis, doing a big big hack!")
			print(f"	((void(*)(void)){node.name}_new)();")
			return
	
	arg_names = [arg.name for arg in node.type.args if hasattr(arg, "name")]
	args = ', '.join(arg_names) if arg_names and arg_names[0] != None else ''
	
	have_ret = node.type.type.type.names[0] != 'void' if type(node.type.type) != PtrDecl else True
	
	print(f"\t{'return ' if have_ret else ''}{node.name}_new({args});")

class FunctionVisitor(NodeVisitor):
	def visit_Decl(self, node):
		if type(node.type) == FuncDecl:
			base_name = node.name
			
			if base_name in SEEN:
				return
			else:
				SEEN.add(base_name)
			
			node.storage = []
			if type(node.type.type) == PtrDecl:
				node.type.type.type.declname += "_old"
			else:
				node.type.type.declname += "_old"
			print(CGenerator().visit(node), "{")
			# print(node.type)
			printcall(node)
			print("}\n")

for filename in os.listdir():
	ast = pycparser.parse_file(
		filename,
		use_cpp=True,
		cpp_args=['-E', '-I/home/knot/Development/Hack/fake_libc_include']
	)
	
	FunctionVisitor().visit(ast)

