// Auto generated by gen_hooks.py

void lua_upgrade_hook51(void) {
	if (!YipReplaceFunction("lua_newstate", lua_newstate_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newstate");
	}
	if (!YipReplaceFunction("lua_close", lua_close_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_close");
	}
	if (!YipReplaceFunction("lua_newthread", lua_newthread_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newthread");
	}
	if (!YipReplaceFunction("lua_atpanic", lua_atpanic_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_atpanic");
	}
	if (!YipReplaceFunction("lua_gettop", lua_gettop_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettop");
	}
	if (!YipReplaceFunction("lua_settop", lua_settop_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settop");
	}
	if (!YipReplaceFunction("lua_pushvalue", lua_pushvalue_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvalue");
	}
	if (!YipReplaceFunction("lua_remove", lua_remove_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_remove");
	}
	if (!YipReplaceFunction("lua_insert", lua_insert_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_insert");
	}
	if (!YipReplaceFunction("lua_replace", lua_replace_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_replace");
	}
	if (!YipReplaceFunction("lua_checkstack", lua_checkstack_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_checkstack");
	}
	if (!YipReplaceFunction("lua_xmove", lua_xmove_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_xmove");
	}
	if (!YipReplaceFunction("lua_isnumber", lua_isnumber_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isnumber");
	}
	if (!YipReplaceFunction("lua_isstring", lua_isstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isstring");
	}
	if (!YipReplaceFunction("lua_iscfunction", lua_iscfunction_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_iscfunction");
	}
	if (!YipReplaceFunction("lua_isuserdata", lua_isuserdata_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isuserdata");
	}
	if (!YipReplaceFunction("lua_type", lua_type_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_type");
	}
	if (!YipReplaceFunction("lua_typename", lua_typename_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_typename");
	}
	if (!YipReplaceFunction("lua_equal", lua_equal_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_equal");
	}
	if (!YipReplaceFunction("lua_rawequal", lua_rawequal_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawequal");
	}
	if (!YipReplaceFunction("lua_lessthan", lua_lessthan_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_lessthan");
	}
	if (!YipReplaceFunction("lua_tonumber", lua_tonumber_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tonumber");
	}
	if (!YipReplaceFunction("lua_tointeger", lua_tointeger_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tointeger");
	}
	if (!YipReplaceFunction("lua_toboolean", lua_toboolean_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_toboolean");
	}
	if (!YipReplaceFunction("lua_tolstring", lua_tolstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tolstring");
	}
	if (!YipReplaceFunction("lua_objlen", lua_objlen_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_objlen");
	}
	if (!YipReplaceFunction("lua_tocfunction", lua_tocfunction_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tocfunction");
	}
	if (!YipReplaceFunction("lua_touserdata", lua_touserdata_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_touserdata");
	}
	if (!YipReplaceFunction("lua_tothread", lua_tothread_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tothread");
	}
	if (!YipReplaceFunction("lua_topointer", lua_topointer_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_topointer");
	}
	if (!YipReplaceFunction("lua_pushnil", lua_pushnil_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnil");
	}
	if (!YipReplaceFunction("lua_pushnumber", lua_pushnumber_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnumber");
	}
	if (!YipReplaceFunction("lua_pushinteger", lua_pushinteger_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushinteger");
	}
	if (!YipReplaceFunction("lua_pushlstring", lua_pushlstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlstring");
	}
	if (!YipReplaceFunction("lua_pushstring", lua_pushstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushstring");
	}
	if (!YipReplaceFunction("lua_pushvfstring", lua_pushvfstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvfstring");
	}
	if (!YipReplaceFunction("lua_pushfstring", lua_pushfstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushfstring");
	}
	if (!YipReplaceFunction("lua_pushcclosure", lua_pushcclosure_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushcclosure");
	}
	if (!YipReplaceFunction("lua_pushboolean", lua_pushboolean_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushboolean");
	}
	if (!YipReplaceFunction("lua_pushlightuserdata", lua_pushlightuserdata_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlightuserdata");
	}
	if (!YipReplaceFunction("lua_pushthread", lua_pushthread_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushthread");
	}
	if (!YipReplaceFunction("lua_gettable", lua_gettable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettable");
	}
	if (!YipReplaceFunction("lua_getfield", lua_getfield_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfield");
	}
	if (!YipReplaceFunction("lua_rawget", lua_rawget_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawget");
	}
	if (!YipReplaceFunction("lua_rawgeti", lua_rawgeti_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawgeti");
	}
	if (!YipReplaceFunction("lua_createtable", lua_createtable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_createtable");
	}
	if (!YipReplaceFunction("lua_newuserdata", lua_newuserdata_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newuserdata");
	}
	if (!YipReplaceFunction("lua_getmetatable", lua_getmetatable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getmetatable");
	}
	if (!YipReplaceFunction("lua_getfenv", lua_getfenv_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfenv");
	}
	if (!YipReplaceFunction("lua_settable", lua_settable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settable");
	}
	if (!YipReplaceFunction("lua_setfield", lua_setfield_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfield");
	}
	if (!YipReplaceFunction("lua_rawset", lua_rawset_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawset");
	}
	if (!YipReplaceFunction("lua_rawseti", lua_rawseti_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawseti");
	}
	if (!YipReplaceFunction("lua_setmetatable", lua_setmetatable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setmetatable");
	}
	if (!YipReplaceFunction("lua_setfenv", lua_setfenv_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfenv");
	}
	if (!YipReplaceFunction("lua_call", lua_call_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_call");
	}
	if (!YipReplaceFunction("lua_pcall", lua_pcall_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pcall");
	}
	if (!YipReplaceFunction("lua_cpcall", lua_cpcall_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_cpcall");
	}
	if (!YipReplaceFunction("lua_load", lua_load_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_load");
	}
	if (!YipReplaceFunction("lua_dump", lua_dump_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_dump");
	}
	if (!YipReplaceFunction("lua_yield", lua_yield_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_yield");
	}
	if (!YipReplaceFunction("lua_resume", lua_resume_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_resume");
	}
	if (!YipReplaceFunction("lua_status", lua_status_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_status");
	}
	if (!YipReplaceFunction("lua_gc", lua_gc_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gc");
	}
	if (!YipReplaceFunction("lua_error", lua_error_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_error");
	}
	if (!YipReplaceFunction("lua_next", lua_next_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_next");
	}
	if (!YipReplaceFunction("lua_concat", lua_concat_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_concat");
	}
	if (!YipReplaceFunction("lua_getallocf", lua_getallocf_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getallocf");
	}
	if (!YipReplaceFunction("lua_setallocf", lua_setallocf_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setallocf");
	}
	if (!YipReplaceFunction("lua_setlevel", lua_setlevel_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlevel");
	}
	if (!YipReplaceFunction("lua_getstack", lua_getstack_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getstack");
	}
	if (!YipReplaceFunction("lua_getinfo", lua_getinfo_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getinfo");
	}
	if (!YipReplaceFunction("lua_getlocal", lua_getlocal_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getlocal");
	}
	if (!YipReplaceFunction("lua_setlocal", lua_setlocal_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlocal");
	}
	if (!YipReplaceFunction("lua_getupvalue", lua_getupvalue_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getupvalue");
	}
	if (!YipReplaceFunction("lua_setupvalue", lua_setupvalue_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setupvalue");
	}
	if (!YipReplaceFunction("lua_sethook", lua_sethook_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_sethook");
	}
	if (!YipReplaceFunction("lua_gethook", lua_gethook_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethook");
	}
	if (!YipReplaceFunction("lua_gethookmask", lua_gethookmask_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookmask");
	}
	if (!YipReplaceFunction("lua_gethookcount", lua_gethookcount_old)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookcount");
	}
	if (!YipReplaceFunction("luaopen_base", luaopen_base_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_base");
	}
	if (!YipReplaceFunction("luaopen_table", luaopen_table_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_table");
	}
	if (!YipReplaceFunction("luaopen_io", luaopen_io_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_io");
	}
	if (!YipReplaceFunction("luaopen_os", luaopen_os_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_os");
	}
	if (!YipReplaceFunction("luaopen_string", luaopen_string_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_string");
	}
	if (!YipReplaceFunction("luaopen_math", luaopen_math_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_math");
	}
	if (!YipReplaceFunction("luaopen_debug", luaopen_debug_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_debug");
	}
	if (!YipReplaceFunction("luaopen_package", luaopen_package_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_package");
	}
	if (!YipReplaceFunction("luaL_openlibs", luaL_openlibs_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_openlibs");
	}
	if (!YipReplaceFunction("luaL_openlib", luaL_openlib_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_openlib");
	}
	if (!YipReplaceFunction("luaL_register", luaL_register_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_register");
	}
	if (!YipReplaceFunction("luaL_getmetafield", luaL_getmetafield_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_getmetafield");
	}
	if (!YipReplaceFunction("luaL_callmeta", luaL_callmeta_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_callmeta");
	}
	if (!YipReplaceFunction("luaL_typerror", luaL_typerror_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_typerror");
	}
	if (!YipReplaceFunction("luaL_argerror", luaL_argerror_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_argerror");
	}
	if (!YipReplaceFunction("luaL_checklstring", luaL_checklstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checklstring");
	}
	if (!YipReplaceFunction("luaL_optlstring", luaL_optlstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optlstring");
	}
	if (!YipReplaceFunction("luaL_checknumber", luaL_checknumber_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checknumber");
	}
	if (!YipReplaceFunction("luaL_optnumber", luaL_optnumber_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optnumber");
	}
	if (!YipReplaceFunction("luaL_checkinteger", luaL_checkinteger_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkinteger");
	}
	if (!YipReplaceFunction("luaL_optinteger", luaL_optinteger_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optinteger");
	}
	if (!YipReplaceFunction("luaL_checkstack", luaL_checkstack_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkstack");
	}
	if (!YipReplaceFunction("luaL_checktype", luaL_checktype_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checktype");
	}
	if (!YipReplaceFunction("luaL_checkany", luaL_checkany_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkany");
	}
	if (!YipReplaceFunction("luaL_newmetatable", luaL_newmetatable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_newmetatable");
	}
	if (!YipReplaceFunction("luaL_checkudata", luaL_checkudata_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkudata");
	}
	if (!YipReplaceFunction("luaL_where", luaL_where_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_where");
	}
	if (!YipReplaceFunction("luaL_error", luaL_error_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_error");
	}
	if (!YipReplaceFunction("luaL_checkoption", luaL_checkoption_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkoption");
	}
	if (!YipReplaceFunction("luaL_ref", luaL_ref_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_ref");
	}
	if (!YipReplaceFunction("luaL_unref", luaL_unref_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_unref");
	}
	if (!YipReplaceFunction("luaL_loadfile", luaL_loadfile_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadfile");
	}
	if (!YipReplaceFunction("luaL_loadbuffer", luaL_loadbuffer_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadbuffer");
	}
	if (!YipReplaceFunction("luaL_loadstring", luaL_loadstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadstring");
	}
	if (!YipReplaceFunction("luaL_newstate", luaL_newstate_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_newstate");
	}
	if (!YipReplaceFunction("luaL_gsub", luaL_gsub_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_gsub");
	}
	if (!YipReplaceFunction("luaL_findtable", luaL_findtable_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_findtable");
	}
	if (!YipReplaceFunction("luaL_buffinit", luaL_buffinit_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_buffinit");
	}
	if (!YipReplaceFunction("luaL_prepbuffer", luaL_prepbuffer_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_prepbuffer");
	}
	if (!YipReplaceFunction("luaL_addlstring", luaL_addlstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addlstring");
	}
	if (!YipReplaceFunction("luaL_addstring", luaL_addstring_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addstring");
	}
	if (!YipReplaceFunction("luaL_addvalue", luaL_addvalue_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addvalue");
	}
	if (!YipReplaceFunction("luaL_pushresult", luaL_pushresult_old)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_pushresult");
	}
}
