/**
 * (Tries) to upgrade Lua despite it being statically linked, also provides a
 * little shim so it will work.
 */

#include <yiploader/yiploader.h>
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include "../util.h"
#include "../builtin/lua_utils.h"

void *liblua;

typedef unsigned long long lua_Unsigned;

#define LUA_OPEQ	0
#define LUA_OPLT	1
#define LUA_OPLE	2

#define LUAI_MAXSTACK		1000000 // HACK but We don't have a 16bit machine :)
#define LUAI_FIRSTPSEUDOIDX	(-LUAI_MAXSTACK - 1000)
#define LUA_REGISTRYINDEX_NEW	LUAI_FIRSTPSEUDOIDX
#define lua_upvalueindex_new(i)	(LUA_REGISTRYINDEX_NEW - (i))

#include "lua52_loader.c"

// int called_times = 0;

static inline int convert_index(int idx) {
	// if (called_times++ > 4500) {
	// 	abort();
	// }
	
	// Convert legacy upvalue index to 5.2 one
	if (idx < LUA_GLOBALSINDEX && idx > LUA_GLOBALSINDEX-256) {
		// For 5.1:   up(i) = LUA_GLOBALSINDEX  - i
		//            up(i) - LUA_GLOBALSINDEX = -i
		//          -(up(i) - LUA_GLOBALSINDEX) = i
		//           -up(i) + LUA_GLOBALSINDEX =  i
		//            LUA_GLOBALSINDEX - up(i) =  i
		int newidx = lua_upvalueindex_new(LUA_GLOBALSINDEX - idx);
		// LogI("lua_upgrade: Covert index %d -> %d", idx, newidx);
		return newidx;
	}
	else {
		return idx;
	}
}

// Auto generated by gen_shims.py
lua_State *lua_newstate_old(lua_Alloc f, void *ud) {
	return lua_newstate_new(f, ud);
}

void lua_close_old(lua_State *L) {
	lua_close_new(L);
}

lua_State *lua_newthread_old(lua_State *L) {
	return lua_newthread_new(L);
}

lua_CFunction lua_atpanic_old(lua_State *L, lua_CFunction panicf) {
	return lua_atpanic_new(L, panicf);
}

int lua_gettop_old(lua_State *L) {
	return lua_gettop_new(L);
}

void lua_settop_old(lua_State *L, int idx) {
	lua_settop_new(L, idx);
}

void lua_pushvalue_old(lua_State *L, int idx) {
	lua_pushvalue_new(L, idx);
}

void lua_remove_old(lua_State *L, int idx) {
	lua_remove_new(L, idx);
}

void lua_insert_old(lua_State *L, int idx) {
	lua_insert_new(L, idx);
}

void lua_replace_old(lua_State *L, int idx) {
	lua_replace_new(L, idx);
}

int lua_checkstack_old(lua_State *L, int sz) {
	return lua_checkstack_new(L, sz);
}

void lua_xmove_old(lua_State *from, lua_State *to, int n) {
	lua_xmove_new(from, to, n);
}

int lua_isnumber_old(lua_State *L, int idx) {
	return lua_isnumber_new(L, idx);
}

int lua_isstring_old(lua_State *L, int idx) {
	return lua_isstring_new(L, idx);
}

int lua_iscfunction_old(lua_State *L, int idx) {
	return lua_iscfunction_new(L, idx);
}

int lua_isuserdata_old(lua_State *L, int idx) {
	return lua_isuserdata_new(L, idx);
}

int lua_type_old(lua_State *L, int idx) {
	return lua_type_new(L, idx);
}

const char *lua_typename_old(lua_State *L, int tp) {
	return lua_typename_new(L, tp);
}

int lua_equal_old(lua_State *L, int idx1, int idx2) {
	return lua_compare_new(L, idx1, idx2, LUA_OPEQ); // 5.2
}

int lua_rawequal_old(lua_State *L, int idx1, int idx2) {
	return lua_rawequal_new(L, idx1, idx2);
}

int lua_lessthan_old(lua_State *L, int idx1, int idx2) {
	return lua_compare_new(L, idx1, idx2, LUA_OPLT); // 5.2
}

lua_Number lua_tonumber_old(lua_State *L, int idx) {
	return lua_tonumberx_new(L, convert_index(idx), NULL); // 5.2
}

lua_Integer lua_tointeger_old(lua_State *L, int idx) {
	return lua_tointegerx_new(L, convert_index(idx), NULL); // 5.2
}

int lua_toboolean_old(lua_State *L, int idx) {
	return lua_toboolean_new(L, convert_index(idx));
}

const char *lua_tolstring_old(lua_State *L, int idx, size_t *len) {
	return lua_tolstring_new(L, convert_index(idx), len);
}

size_t lua_objlen_old(lua_State *L, int idx) {
	return lua_rawlen_new(L, idx); // 5.2: Rename objlen -> rawlen
}

lua_CFunction lua_tocfunction_old(lua_State *L, int idx) {
	return lua_tocfunction_new(L, convert_index(idx));
}

void *lua_touserdata_old(lua_State *L, int idx) {
	return lua_touserdata_new(L, convert_index(idx));
}

lua_State *lua_tothread_old(lua_State *L, int idx) {
	return lua_tothread_new(L, convert_index(idx));
}

const void *lua_topointer_old(lua_State *L, int idx) {
	return lua_topointer_new(L, convert_index(idx));
}

void lua_pushnil_old(lua_State *L) {
	lua_pushnil_new(L);
}

void lua_pushnumber_old(lua_State *L, lua_Number n) {
	lua_pushnumber_new(L, n);
}

void lua_pushinteger_old(lua_State *L, lua_Integer n) {
	lua_pushinteger_new(L, n);
}

void lua_pushlstring_old(lua_State *L, const char *s, size_t l) {
	lua_pushlstring_new(L, s, l);
}

void lua_pushstring_old(lua_State *L, const char *s) {
	lua_pushstring_new(L, s);
}

const char *lua_pushvfstring_old(lua_State *L, const char *fmt, va_list argp) {
	return lua_pushvfstring_new(L, fmt, argp);
}

const char *lua_pushfstring_old(lua_State *L, const char *fmt, ...) {
	const char *ret;
	va_list argp;
	va_start(argp, fmt);
	ret = lua_pushvfstring_new(L, fmt, argp);
	va_end(argp);
	return ret;
}

void lua_pushcclosure_old(lua_State *L, lua_CFunction fn, int n) {
	lua_pushcclosure_new(L, fn, n);
}

void lua_pushboolean_old(lua_State *L, int b) {
	lua_pushboolean_new(L, b);
}

void lua_pushlightuserdata_old(lua_State *L, void *p) {
	lua_pushlightuserdata_new(L, p);
}

int lua_pushthread_old(lua_State *L) {
	return lua_pushthread_new(L);
}

void lua_gettable_old(lua_State *L, int idx) {
	lua_gettable_new(L, idx);
}

void lua_getfield_old(lua_State *L, int idx, const char *k) {
	if (idx == LUA_GLOBALSINDEX) {
		lua_getglobal_new(L, k);
	}
	else {
		lua_getfield_new(L, idx, k);
	}
}

void lua_rawget_old(lua_State *L, int idx) {
	lua_rawget_new(L, idx);
}

void lua_rawgeti_old(lua_State *L, int idx, int n) {
	lua_rawgeti_new(L, idx, n);
}

void lua_createtable_old(lua_State *L, int narr, int nrec) {
	lua_createtable_new(L, narr, nrec);
}

void *lua_newuserdata_old(lua_State *L, size_t sz) {
	return lua_newuserdata_new(L, sz);
}

int lua_getmetatable_old(lua_State *L, int objindex) {
	return lua_getmetatable_new(L, objindex);
}

void lua_getfenv_old(lua_State *L, int idx) {
	// TODO 5.2
	luaL_error_new(L, "lua_setfenv is not implemented anymore");
}

void lua_settable_old(lua_State *L, int idx) {
	lua_settable_new(L, idx);
}

void lua_setfield_old(lua_State *L, int idx, const char *k) {
	if (idx == LUA_GLOBALSINDEX) {
		lua_setglobal_new(L, k);
	}
	else {
		lua_setfield_new(L, idx, k);
	}
}

void lua_rawset_old(lua_State *L, int idx) {
	lua_rawset_new(L, idx);
}

void lua_rawseti_old(lua_State *L, int idx, int n) {
	lua_rawseti_new(L, idx, n);
}

int lua_setmetatable_old(lua_State *L, int objindex) {
	return lua_setmetatable_new(L, objindex);
}

int lua_setfenv_old(lua_State *L, int idx) {
	// 5.2
	// TODO: Find some way to reimplement this properly
	// return lua_setfenv_new(L, idx);
	return luaL_error_new(L, "lua_setfenv is not implemented anymore");
}

void lua_call_old(lua_State *L, int nargs, int nresults) {
	lua_callk_new(L, nargs, nresults, 0, NULL); // 5.2
}

int lua_pcall_old(lua_State *L, int nargs, int nresults, int errfunc) {
	return lua_pcallk_new(L, nargs, nresults, errfunc, 0, NULL); // 5.2
}

int lua_cpcall_old(lua_State *L, lua_CFunction func, void *ud) {
	// 5.2 deprecated cpcall
	lua_pushcclosure_new(L, func, 0);
	lua_pushlightuserdata_new(L, ud);
	return lua_pcallk_new(L, 1, 0, 0, 0, NULL);
}

int lua_load_old(lua_State *L, lua_Reader reader, void *dt, const char *chunkname) {
	return lua_load_new(L, reader, dt, chunkname, NULL);
}

int lua_dump_old(lua_State *L, lua_Writer writer, void *data) {
	return lua_dump_new(L, writer, data);
}

int lua_yield_old(lua_State *L, int nresults) {
	return lua_yieldk_new(L, nresults, 0, NULL); // 5.2
}

int lua_resume_old(lua_State *L, int narg) {
	return lua_resume_new(L, NULL, narg);
}

int lua_status_old(lua_State *L) {
	return lua_status_new(L);
}

int lua_gc_old(lua_State *L, int what, int data) {
	return lua_gc_new(L, what, data);
}

int lua_error_old(lua_State *L) {
	return lua_error_new(L);
}

int lua_next_old(lua_State *L, int idx) {
	return lua_next_new(L, idx);
}

void lua_concat_old(lua_State *L, int n) {
	lua_concat_new(L, n);
}

lua_Alloc lua_getallocf_old(lua_State *L, void **ud) {
	return lua_getallocf_new(L, ud);
}

void lua_setallocf_old(lua_State *L, lua_Alloc f, void *ud) {
	lua_setallocf_new(L, f, ud);
}

void lua_setlevel_old(lua_State *from, lua_State *to) {
	// Removed 5.2 w/o documentation of that - was labelled "hack" in 5.1 so I
	// assume it was not supposed to be a public API anyway.
}

int lua_getstack_old(lua_State *L, int level, lua_Debug *ar) {
	return lua_getstack_new(L, level, ar);
}

int lua_getinfo_old(lua_State *L, const char *what, lua_Debug *ar) {
	return lua_getinfo_new(L, what, ar);
}

const char *lua_getlocal_old(lua_State *L, const lua_Debug *ar, int n) {
	return lua_getlocal_new(L, ar, n);
}

const char *lua_setlocal_old(lua_State *L, const lua_Debug *ar, int n) {
	return lua_setlocal_new(L, ar, n);
}

const char *lua_getupvalue_old(lua_State *L, int funcindex, int n) {
	return lua_getupvalue_new(L, funcindex, n);
}

const char *lua_setupvalue_old(lua_State *L, int funcindex, int n) {
	return lua_setupvalue_new(L, funcindex, n);
}

int lua_sethook_old(lua_State *L, lua_Hook func, int mask, int count) {
	return lua_sethook_new(L, func, mask, count);
}

lua_Hook lua_gethook_old(lua_State *L) {
	return lua_gethook_new(L);
}

int lua_gethookmask_old(lua_State *L) {
	return lua_gethookmask_new(L);
}

int lua_gethookcount_old(lua_State *L) {
	return lua_gethookcount_new(L);
}

int luaopen_base_old(lua_State *L) {
	return luaopen_base_new(L);
}

int luaopen_table_old(lua_State *L) {
	return luaopen_table_new(L);
}

int luaopen_io_old(lua_State *L) {
	return luaopen_io_new(L);
}

int luaopen_os_old(lua_State *L) {
	return luaopen_os_new(L);
}

int luaopen_string_old(lua_State *L) {
	return luaopen_string_new(L);
}

int luaopen_math_old(lua_State *L) {
	return luaopen_math_new(L);
}

int luaopen_debug_old(lua_State *L) {
	return luaopen_debug_new(L);
}

int luaopen_package_old(lua_State *L) {
	return luaopen_package_new(L);
}

void luaL_openlibs_old(lua_State *L) {
	luaL_openlibs_new(L);
}

void luaL_openlib_old(lua_State *L, const char *libname, const luaL_Reg *l, int nup) {
	// 5.2 Removed -- TODO find alternative? not sure if its needed tho
}

void luaL_register_old(lua_State *L, const char *libname, const luaL_Reg *l) {
	// 5.2 Removed
	// TODO: This is a very, very poor substitute for the 5.1 way of doing
	// things, but it should work okay since we don't really use luaL_register.
	if (libname) lua_createtable_new(L, 0, 0);
	luaL_setfuncs_new(L, l, 0);
	if (libname) lua_setglobal_new(L, libname);
}

int luaL_getmetafield_old(lua_State *L, int obj, const char *e) {
	return luaL_getmetafield_new(L, obj, e);
}

int luaL_callmeta_old(lua_State *L, int obj, const char *e) {
	return luaL_callmeta_new(L, obj, e);
}

int luaL_typerror_old(lua_State *L, int narg, const char *tname) {
	// 5.2 Removed, simple to reimplement though
	const char *msg = lua_pushfstring_new(L, "%s expected, got %s", tname, luaL_typename(L, narg));
	return luaL_argerror_new(L, narg, msg);
}

int luaL_argerror_old(lua_State *L, int numarg, const char *extramsg) {
	return luaL_argerror_new(L, numarg, extramsg);
}

const char *luaL_checklstring_old(lua_State *L, int numArg, size_t *l) {
	return luaL_checklstring_new(L, numArg, l);
}

const char *luaL_optlstring_old(lua_State *L, int numArg, const char *def, size_t *l) {
	return luaL_optlstring_new(L, numArg, def, l);
}

lua_Number luaL_checknumber_old(lua_State *L, int numArg) {
	return luaL_checknumber_new(L, numArg);
}

lua_Number luaL_optnumber_old(lua_State *L, int nArg, lua_Number def) {
	return luaL_optnumber_new(L, nArg, def);
}

lua_Integer luaL_checkinteger_old(lua_State *L, int numArg) {
	return luaL_checkinteger_new(L, numArg);
}

lua_Integer luaL_optinteger_old(lua_State *L, int nArg, lua_Integer def) {
	return luaL_optinteger_new(L, nArg, def);
}

void luaL_checkstack_old(lua_State *L, int sz, const char *msg) {
	luaL_checkstack_new(L, sz, msg);
}

void luaL_checktype_old(lua_State *L, int narg, int t) {
	luaL_checktype_new(L, narg, t);
}

void luaL_checkany_old(lua_State *L, int narg) {
	luaL_checkany_new(L, narg);
}

int luaL_newmetatable_old(lua_State *L, const char *tname) {
	return luaL_newmetatable_new(L, tname);
}

void *luaL_checkudata_old(lua_State *L, int ud, const char *tname) {
	return luaL_checkudata_new(L, ud, tname);
}

void luaL_where_old(lua_State *L, int lvl) {
	luaL_where_new(L, lvl);
}

int luaL_error_old(lua_State *L, const char *fmt, ...) {
	va_list argp;
	va_start(argp, fmt);
	luaL_where_new(L, 1);
	lua_pushvfstring_new(L, fmt, argp);
	va_end(argp);
	lua_concat_new(L, 2);
	return lua_error_new(L);
}

int luaL_checkoption_old(lua_State *L, int narg, const char *def, const char * const lst[]) {
	return luaL_checkoption_new(L, narg, def, lst);
}

int luaL_ref_old(lua_State *L, int t) {
	return luaL_ref_new(L, t);
}

void luaL_unref_old(lua_State *L, int t, int ref) {
	luaL_unref_new(L, t, ref);
}

int luaL_loadfile_old(lua_State *L, const char *filename) {
	return luaL_loadfilex_new(L, filename, NULL); // 5.2
}

int luaL_loadbuffer_old(lua_State *L, const char *buff, size_t sz, const char *name) {
	return luaL_loadbufferx_new(L, buff, sz, name, NULL); // 5.2
}

int luaL_loadstring_old(lua_State *L, const char *s) {
	return luaL_loadstring_new(L, s);
}

lua_State *luaL_newstate_old(void) {
	return luaL_newstate_new();
}

const char *luaL_gsub_old(lua_State *L, const char *s, const char *p, const char *r) {
	return luaL_gsub_new(L, s, p, r);
}

const char *luaL_findtable_old(lua_State *L, int idx, const char *fname, int szhint) {
	// 5.2 Removed, part of old lib system
	return NULL;
}

void luaL_buffinit_old(lua_State *L, luaL_Buffer *B) {
	luaL_buffinit_new(L, B);
}

char *luaL_prepbuffer_old(luaL_Buffer *B) {
	return luaL_prepbuffsize_new(B, BUFSIZ); // 5.2
}

void luaL_addlstring_old(luaL_Buffer *B, const char *s, size_t l) {
	luaL_addlstring_new(B, s, l);
}

void luaL_addstring_old(luaL_Buffer *B, const char *s) {
	luaL_addstring_new(B, s);
}

void luaL_addvalue_old(luaL_Buffer *B) {
	luaL_addvalue_new(B);
}

void luaL_pushresult_old(luaL_Buffer *B) {
	luaL_pushresult_new(B);
}

#include "lua51_hook.c"

void lua_upgrade(void) {
	liblua = dlopen("liblua.so", RTLD_NOW | RTLD_GLOBAL);
	
	LogI("Will attempt to upgrade Lua to 5.2");
	
	if (liblua) {
		lua_upgrade_load52();
		lua_upgrade_hook51();
	}
	
	LogI("Lua upgrade init finished");
}

const char *KNInitLuaUpgrade(void) {
	lua_upgrade();
	return NULL;
}
