// Auto generated by gen_hooks.py

void lua_upgrade_hook51(void) {
	if (!YipHookFunction("lua_newstate", lua_newstate_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newstate");
	}
	if (!YipHookFunction("lua_close", lua_close_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_close");
	}
	if (!YipHookFunction("lua_newthread", lua_newthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newthread");
	}
	if (!YipHookFunction("lua_atpanic", lua_atpanic_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_atpanic");
	}
	if (!YipHookFunction("lua_gettop", lua_gettop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettop");
	}
	if (!YipHookFunction("lua_settop", lua_settop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settop");
	}
	if (!YipHookFunction("lua_pushvalue", lua_pushvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvalue");
	}
	if (!YipHookFunction("lua_remove", lua_remove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_remove");
	}
	if (!YipHookFunction("lua_insert", lua_insert_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_insert");
	}
	if (!YipHookFunction("lua_replace", lua_replace_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_replace");
	}
	if (!YipHookFunction("lua_checkstack", lua_checkstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_checkstack");
	}
	if (!YipHookFunction("lua_xmove", lua_xmove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_xmove");
	}
	if (!YipHookFunction("lua_isnumber", lua_isnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isnumber");
	}
	if (!YipHookFunction("lua_isstring", lua_isstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isstring");
	}
	if (!YipHookFunction("lua_iscfunction", lua_iscfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_iscfunction");
	}
	if (!YipHookFunction("lua_isuserdata", lua_isuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isuserdata");
	}
	if (!YipHookFunction("lua_type", lua_type_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_type");
	}
	if (!YipHookFunction("lua_typename", lua_typename_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_typename");
	}
	if (!YipHookFunction("lua_equal", lua_equal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_equal");
	}
	if (!YipHookFunction("lua_rawequal", lua_rawequal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawequal");
	}
	if (!YipHookFunction("lua_lessthan", lua_lessthan_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_lessthan");
	}
	if (!YipHookFunction("lua_tonumber", lua_tonumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tonumber");
	}
	if (!YipHookFunction("lua_tointeger", lua_tointeger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tointeger");
	}
	if (!YipHookFunction("lua_toboolean", lua_toboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_toboolean");
	}
	if (!YipHookFunction("lua_tolstring", lua_tolstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tolstring");
	}
	if (!YipHookFunction("lua_objlen", lua_objlen_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_objlen");
	}
	if (!YipHookFunction("lua_tocfunction", lua_tocfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tocfunction");
	}
	if (!YipHookFunction("lua_touserdata", lua_touserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_touserdata");
	}
	if (!YipHookFunction("lua_tothread", lua_tothread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tothread");
	}
	if (!YipHookFunction("lua_topointer", lua_topointer_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_topointer");
	}
	if (!YipHookFunction("lua_pushnil", lua_pushnil_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnil");
	}
	if (!YipHookFunction("lua_pushnumber", lua_pushnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnumber");
	}
	if (!YipHookFunction("lua_pushinteger", lua_pushinteger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushinteger");
	}
	if (!YipHookFunction("lua_pushlstring", lua_pushlstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlstring");
	}
	if (!YipHookFunction("lua_pushstring", lua_pushstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushstring");
	}
	if (!YipHookFunction("lua_pushvfstring", lua_pushvfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvfstring");
	}
	if (!YipHookFunction("lua_pushfstring", lua_pushfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushfstring");
	}
	if (!YipHookFunction("lua_pushcclosure", lua_pushcclosure_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushcclosure");
	}
	if (!YipHookFunction("lua_pushboolean", lua_pushboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushboolean");
	}
	if (!YipHookFunction("lua_pushlightuserdata", lua_pushlightuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlightuserdata");
	}
	if (!YipHookFunction("lua_pushthread", lua_pushthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushthread");
	}
	if (!YipHookFunction("lua_gettable", lua_gettable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettable");
	}
	if (!YipHookFunction("lua_getfield", lua_getfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfield");
	}
	if (!YipHookFunction("lua_rawget", lua_rawget_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawget");
	}
	if (!YipHookFunction("lua_rawgeti", lua_rawgeti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawgeti");
	}
	if (!YipHookFunction("lua_createtable", lua_createtable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_createtable");
	}
	if (!YipHookFunction("lua_newuserdata", lua_newuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newuserdata");
	}
	if (!YipHookFunction("lua_getmetatable", lua_getmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getmetatable");
	}
	if (!YipHookFunction("lua_getfenv", lua_getfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfenv");
	}
	if (!YipHookFunction("lua_settable", lua_settable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settable");
	}
	if (!YipHookFunction("lua_setfield", lua_setfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfield");
	}
	if (!YipHookFunction("lua_rawset", lua_rawset_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawset");
	}
	if (!YipHookFunction("lua_rawseti", lua_rawseti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawseti");
	}
	if (!YipHookFunction("lua_setmetatable", lua_setmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setmetatable");
	}
	if (!YipHookFunction("lua_setfenv", lua_setfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfenv");
	}
	if (!YipHookFunction("lua_call", lua_call_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_call");
	}
	if (!YipHookFunction("lua_pcall", lua_pcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pcall");
	}
	if (!YipHookFunction("lua_cpcall", lua_cpcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_cpcall");
	}
	if (!YipHookFunction("lua_load", lua_load_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_load");
	}
	if (!YipHookFunction("lua_dump", lua_dump_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_dump");
	}
	if (!YipHookFunction("lua_yield", lua_yield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_yield");
	}
	if (!YipHookFunction("lua_resume", lua_resume_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_resume");
	}
	if (!YipHookFunction("lua_status", lua_status_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_status");
	}
	if (!YipHookFunction("lua_gc", lua_gc_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gc");
	}
	if (!YipHookFunction("lua_error", lua_error_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_error");
	}
	if (!YipHookFunction("lua_next", lua_next_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_next");
	}
	if (!YipHookFunction("lua_concat", lua_concat_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_concat");
	}
	if (!YipHookFunction("lua_getallocf", lua_getallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getallocf");
	}
	if (!YipHookFunction("lua_setallocf", lua_setallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setallocf");
	}
	if (!YipHookFunction("lua_setlevel", lua_setlevel_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlevel");
	}
	if (!YipHookFunction("lua_getstack", lua_getstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getstack");
	}
	if (!YipHookFunction("lua_getinfo", lua_getinfo_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getinfo");
	}
	if (!YipHookFunction("lua_getlocal", lua_getlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getlocal");
	}
	if (!YipHookFunction("lua_setlocal", lua_setlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlocal");
	}
	if (!YipHookFunction("lua_getupvalue", lua_getupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getupvalue");
	}
	if (!YipHookFunction("lua_setupvalue", lua_setupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setupvalue");
	}
	if (!YipHookFunction("lua_sethook", lua_sethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_sethook");
	}
	if (!YipHookFunction("lua_gethook", lua_gethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethook");
	}
	if (!YipHookFunction("lua_gethookmask", lua_gethookmask_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookmask");
	}
	if (!YipHookFunction("lua_gethookcount", lua_gethookcount_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookcount");
	}
	if (!YipHookFunction("luaopen_base", luaopen_base_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_base");
	}
	if (!YipHookFunction("luaopen_table", luaopen_table_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_table");
	}
	if (!YipHookFunction("luaopen_io", luaopen_io_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_io");
	}
	if (!YipHookFunction("luaopen_os", luaopen_os_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_os");
	}
	if (!YipHookFunction("luaopen_string", luaopen_string_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_string");
	}
	if (!YipHookFunction("luaopen_math", luaopen_math_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_math");
	}
	if (!YipHookFunction("luaopen_debug", luaopen_debug_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_debug");
	}
	if (!YipHookFunction("luaopen_package", luaopen_package_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaopen_package");
	}
	if (!YipHookFunction("luaL_openlibs", luaL_openlibs_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_openlibs");
	}
	if (!YipHookFunction("lua_newstate", lua_newstate_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newstate");
	}
	if (!YipHookFunction("lua_close", lua_close_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_close");
	}
	if (!YipHookFunction("lua_newthread", lua_newthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newthread");
	}
	if (!YipHookFunction("lua_atpanic", lua_atpanic_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_atpanic");
	}
	if (!YipHookFunction("lua_gettop", lua_gettop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettop");
	}
	if (!YipHookFunction("lua_settop", lua_settop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settop");
	}
	if (!YipHookFunction("lua_pushvalue", lua_pushvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvalue");
	}
	if (!YipHookFunction("lua_remove", lua_remove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_remove");
	}
	if (!YipHookFunction("lua_insert", lua_insert_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_insert");
	}
	if (!YipHookFunction("lua_replace", lua_replace_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_replace");
	}
	if (!YipHookFunction("lua_checkstack", lua_checkstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_checkstack");
	}
	if (!YipHookFunction("lua_xmove", lua_xmove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_xmove");
	}
	if (!YipHookFunction("lua_isnumber", lua_isnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isnumber");
	}
	if (!YipHookFunction("lua_isstring", lua_isstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isstring");
	}
	if (!YipHookFunction("lua_iscfunction", lua_iscfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_iscfunction");
	}
	if (!YipHookFunction("lua_isuserdata", lua_isuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isuserdata");
	}
	if (!YipHookFunction("lua_type", lua_type_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_type");
	}
	if (!YipHookFunction("lua_typename", lua_typename_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_typename");
	}
	if (!YipHookFunction("lua_equal", lua_equal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_equal");
	}
	if (!YipHookFunction("lua_rawequal", lua_rawequal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawequal");
	}
	if (!YipHookFunction("lua_lessthan", lua_lessthan_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_lessthan");
	}
	if (!YipHookFunction("lua_tonumber", lua_tonumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tonumber");
	}
	if (!YipHookFunction("lua_tointeger", lua_tointeger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tointeger");
	}
	if (!YipHookFunction("lua_toboolean", lua_toboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_toboolean");
	}
	if (!YipHookFunction("lua_tolstring", lua_tolstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tolstring");
	}
	if (!YipHookFunction("lua_objlen", lua_objlen_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_objlen");
	}
	if (!YipHookFunction("lua_tocfunction", lua_tocfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tocfunction");
	}
	if (!YipHookFunction("lua_touserdata", lua_touserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_touserdata");
	}
	if (!YipHookFunction("lua_tothread", lua_tothread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tothread");
	}
	if (!YipHookFunction("lua_topointer", lua_topointer_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_topointer");
	}
	if (!YipHookFunction("lua_pushnil", lua_pushnil_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnil");
	}
	if (!YipHookFunction("lua_pushnumber", lua_pushnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnumber");
	}
	if (!YipHookFunction("lua_pushinteger", lua_pushinteger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushinteger");
	}
	if (!YipHookFunction("lua_pushlstring", lua_pushlstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlstring");
	}
	if (!YipHookFunction("lua_pushstring", lua_pushstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushstring");
	}
	if (!YipHookFunction("lua_pushvfstring", lua_pushvfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvfstring");
	}
	if (!YipHookFunction("lua_pushfstring", lua_pushfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushfstring");
	}
	if (!YipHookFunction("lua_pushcclosure", lua_pushcclosure_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushcclosure");
	}
	if (!YipHookFunction("lua_pushboolean", lua_pushboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushboolean");
	}
	if (!YipHookFunction("lua_pushlightuserdata", lua_pushlightuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlightuserdata");
	}
	if (!YipHookFunction("lua_pushthread", lua_pushthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushthread");
	}
	if (!YipHookFunction("lua_gettable", lua_gettable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettable");
	}
	if (!YipHookFunction("lua_getfield", lua_getfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfield");
	}
	if (!YipHookFunction("lua_rawget", lua_rawget_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawget");
	}
	if (!YipHookFunction("lua_rawgeti", lua_rawgeti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawgeti");
	}
	if (!YipHookFunction("lua_createtable", lua_createtable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_createtable");
	}
	if (!YipHookFunction("lua_newuserdata", lua_newuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newuserdata");
	}
	if (!YipHookFunction("lua_getmetatable", lua_getmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getmetatable");
	}
	if (!YipHookFunction("lua_getfenv", lua_getfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfenv");
	}
	if (!YipHookFunction("lua_settable", lua_settable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settable");
	}
	if (!YipHookFunction("lua_setfield", lua_setfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfield");
	}
	if (!YipHookFunction("lua_rawset", lua_rawset_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawset");
	}
	if (!YipHookFunction("lua_rawseti", lua_rawseti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawseti");
	}
	if (!YipHookFunction("lua_setmetatable", lua_setmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setmetatable");
	}
	if (!YipHookFunction("lua_setfenv", lua_setfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfenv");
	}
	if (!YipHookFunction("lua_call", lua_call_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_call");
	}
	if (!YipHookFunction("lua_pcall", lua_pcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pcall");
	}
	if (!YipHookFunction("lua_cpcall", lua_cpcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_cpcall");
	}
	if (!YipHookFunction("lua_load", lua_load_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_load");
	}
	if (!YipHookFunction("lua_dump", lua_dump_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_dump");
	}
	if (!YipHookFunction("lua_yield", lua_yield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_yield");
	}
	if (!YipHookFunction("lua_resume", lua_resume_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_resume");
	}
	if (!YipHookFunction("lua_status", lua_status_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_status");
	}
	if (!YipHookFunction("lua_gc", lua_gc_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gc");
	}
	if (!YipHookFunction("lua_error", lua_error_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_error");
	}
	if (!YipHookFunction("lua_next", lua_next_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_next");
	}
	if (!YipHookFunction("lua_concat", lua_concat_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_concat");
	}
	if (!YipHookFunction("lua_getallocf", lua_getallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getallocf");
	}
	if (!YipHookFunction("lua_setallocf", lua_setallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setallocf");
	}
	if (!YipHookFunction("lua_setlevel", lua_setlevel_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlevel");
	}
	if (!YipHookFunction("lua_getstack", lua_getstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getstack");
	}
	if (!YipHookFunction("lua_getinfo", lua_getinfo_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getinfo");
	}
	if (!YipHookFunction("lua_getlocal", lua_getlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getlocal");
	}
	if (!YipHookFunction("lua_setlocal", lua_setlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlocal");
	}
	if (!YipHookFunction("lua_getupvalue", lua_getupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getupvalue");
	}
	if (!YipHookFunction("lua_setupvalue", lua_setupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setupvalue");
	}
	if (!YipHookFunction("lua_sethook", lua_sethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_sethook");
	}
	if (!YipHookFunction("lua_gethook", lua_gethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethook");
	}
	if (!YipHookFunction("lua_gethookmask", lua_gethookmask_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookmask");
	}
	if (!YipHookFunction("lua_gethookcount", lua_gethookcount_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookcount");
	}
	if (!YipHookFunction("luaL_openlib", luaL_openlib_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_openlib");
	}
	if (!YipHookFunction("luaL_register", luaL_register_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_register");
	}
	if (!YipHookFunction("luaL_getmetafield", luaL_getmetafield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_getmetafield");
	}
	if (!YipHookFunction("luaL_callmeta", luaL_callmeta_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_callmeta");
	}
	if (!YipHookFunction("luaL_typerror", luaL_typerror_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_typerror");
	}
	if (!YipHookFunction("luaL_argerror", luaL_argerror_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_argerror");
	}
	if (!YipHookFunction("luaL_checklstring", luaL_checklstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checklstring");
	}
	if (!YipHookFunction("luaL_optlstring", luaL_optlstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optlstring");
	}
	if (!YipHookFunction("luaL_checknumber", luaL_checknumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checknumber");
	}
	if (!YipHookFunction("luaL_optnumber", luaL_optnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optnumber");
	}
	if (!YipHookFunction("luaL_checkinteger", luaL_checkinteger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkinteger");
	}
	if (!YipHookFunction("luaL_optinteger", luaL_optinteger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_optinteger");
	}
	if (!YipHookFunction("luaL_checkstack", luaL_checkstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkstack");
	}
	if (!YipHookFunction("luaL_checktype", luaL_checktype_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checktype");
	}
	if (!YipHookFunction("luaL_checkany", luaL_checkany_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkany");
	}
	if (!YipHookFunction("luaL_newmetatable", luaL_newmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_newmetatable");
	}
	if (!YipHookFunction("luaL_checkudata", luaL_checkudata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkudata");
	}
	if (!YipHookFunction("luaL_where", luaL_where_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_where");
	}
	if (!YipHookFunction("luaL_error", luaL_error_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_error");
	}
	if (!YipHookFunction("luaL_checkoption", luaL_checkoption_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_checkoption");
	}
	if (!YipHookFunction("luaL_ref", luaL_ref_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_ref");
	}
	if (!YipHookFunction("luaL_unref", luaL_unref_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_unref");
	}
	if (!YipHookFunction("luaL_loadfile", luaL_loadfile_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadfile");
	}
	if (!YipHookFunction("luaL_loadbuffer", luaL_loadbuffer_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadbuffer");
	}
	if (!YipHookFunction("luaL_loadstring", luaL_loadstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_loadstring");
	}
	if (!YipHookFunction("luaL_newstate", luaL_newstate_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_newstate");
	}
	if (!YipHookFunction("luaL_gsub", luaL_gsub_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_gsub");
	}
	if (!YipHookFunction("luaL_findtable", luaL_findtable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_findtable");
	}
	if (!YipHookFunction("luaL_buffinit", luaL_buffinit_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_buffinit");
	}
	if (!YipHookFunction("luaL_prepbuffer", luaL_prepbuffer_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_prepbuffer");
	}
	if (!YipHookFunction("luaL_addlstring", luaL_addlstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addlstring");
	}
	if (!YipHookFunction("luaL_addstring", luaL_addstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addstring");
	}
	if (!YipHookFunction("luaL_addvalue", luaL_addvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_addvalue");
	}
	if (!YipHookFunction("luaL_pushresult", luaL_pushresult_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "luaL_pushresult");
	}
	if (!YipHookFunction("lua_newstate", lua_newstate_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newstate");
	}
	if (!YipHookFunction("lua_close", lua_close_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_close");
	}
	if (!YipHookFunction("lua_newthread", lua_newthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newthread");
	}
	if (!YipHookFunction("lua_atpanic", lua_atpanic_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_atpanic");
	}
	if (!YipHookFunction("lua_gettop", lua_gettop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettop");
	}
	if (!YipHookFunction("lua_settop", lua_settop_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settop");
	}
	if (!YipHookFunction("lua_pushvalue", lua_pushvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvalue");
	}
	if (!YipHookFunction("lua_remove", lua_remove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_remove");
	}
	if (!YipHookFunction("lua_insert", lua_insert_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_insert");
	}
	if (!YipHookFunction("lua_replace", lua_replace_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_replace");
	}
	if (!YipHookFunction("lua_checkstack", lua_checkstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_checkstack");
	}
	if (!YipHookFunction("lua_xmove", lua_xmove_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_xmove");
	}
	if (!YipHookFunction("lua_isnumber", lua_isnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isnumber");
	}
	if (!YipHookFunction("lua_isstring", lua_isstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isstring");
	}
	if (!YipHookFunction("lua_iscfunction", lua_iscfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_iscfunction");
	}
	if (!YipHookFunction("lua_isuserdata", lua_isuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_isuserdata");
	}
	if (!YipHookFunction("lua_type", lua_type_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_type");
	}
	if (!YipHookFunction("lua_typename", lua_typename_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_typename");
	}
	if (!YipHookFunction("lua_equal", lua_equal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_equal");
	}
	if (!YipHookFunction("lua_rawequal", lua_rawequal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawequal");
	}
	if (!YipHookFunction("lua_lessthan", lua_lessthan_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_lessthan");
	}
	if (!YipHookFunction("lua_tonumber", lua_tonumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tonumber");
	}
	if (!YipHookFunction("lua_tointeger", lua_tointeger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tointeger");
	}
	if (!YipHookFunction("lua_toboolean", lua_toboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_toboolean");
	}
	if (!YipHookFunction("lua_tolstring", lua_tolstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tolstring");
	}
	if (!YipHookFunction("lua_objlen", lua_objlen_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_objlen");
	}
	if (!YipHookFunction("lua_tocfunction", lua_tocfunction_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tocfunction");
	}
	if (!YipHookFunction("lua_touserdata", lua_touserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_touserdata");
	}
	if (!YipHookFunction("lua_tothread", lua_tothread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_tothread");
	}
	if (!YipHookFunction("lua_topointer", lua_topointer_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_topointer");
	}
	if (!YipHookFunction("lua_pushnil", lua_pushnil_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnil");
	}
	if (!YipHookFunction("lua_pushnumber", lua_pushnumber_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushnumber");
	}
	if (!YipHookFunction("lua_pushinteger", lua_pushinteger_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushinteger");
	}
	if (!YipHookFunction("lua_pushlstring", lua_pushlstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlstring");
	}
	if (!YipHookFunction("lua_pushstring", lua_pushstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushstring");
	}
	if (!YipHookFunction("lua_pushvfstring", lua_pushvfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushvfstring");
	}
	if (!YipHookFunction("lua_pushfstring", lua_pushfstring_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushfstring");
	}
	if (!YipHookFunction("lua_pushcclosure", lua_pushcclosure_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushcclosure");
	}
	if (!YipHookFunction("lua_pushboolean", lua_pushboolean_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushboolean");
	}
	if (!YipHookFunction("lua_pushlightuserdata", lua_pushlightuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushlightuserdata");
	}
	if (!YipHookFunction("lua_pushthread", lua_pushthread_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pushthread");
	}
	if (!YipHookFunction("lua_gettable", lua_gettable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gettable");
	}
	if (!YipHookFunction("lua_getfield", lua_getfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfield");
	}
	if (!YipHookFunction("lua_rawget", lua_rawget_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawget");
	}
	if (!YipHookFunction("lua_rawgeti", lua_rawgeti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawgeti");
	}
	if (!YipHookFunction("lua_createtable", lua_createtable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_createtable");
	}
	if (!YipHookFunction("lua_newuserdata", lua_newuserdata_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_newuserdata");
	}
	if (!YipHookFunction("lua_getmetatable", lua_getmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getmetatable");
	}
	if (!YipHookFunction("lua_getfenv", lua_getfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getfenv");
	}
	if (!YipHookFunction("lua_settable", lua_settable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_settable");
	}
	if (!YipHookFunction("lua_setfield", lua_setfield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfield");
	}
	if (!YipHookFunction("lua_rawset", lua_rawset_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawset");
	}
	if (!YipHookFunction("lua_rawseti", lua_rawseti_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_rawseti");
	}
	if (!YipHookFunction("lua_setmetatable", lua_setmetatable_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setmetatable");
	}
	if (!YipHookFunction("lua_setfenv", lua_setfenv_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setfenv");
	}
	if (!YipHookFunction("lua_call", lua_call_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_call");
	}
	if (!YipHookFunction("lua_pcall", lua_pcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_pcall");
	}
	if (!YipHookFunction("lua_cpcall", lua_cpcall_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_cpcall");
	}
	if (!YipHookFunction("lua_load", lua_load_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_load");
	}
	if (!YipHookFunction("lua_dump", lua_dump_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_dump");
	}
	if (!YipHookFunction("lua_yield", lua_yield_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_yield");
	}
	if (!YipHookFunction("lua_resume", lua_resume_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_resume");
	}
	if (!YipHookFunction("lua_status", lua_status_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_status");
	}
	if (!YipHookFunction("lua_gc", lua_gc_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gc");
	}
	if (!YipHookFunction("lua_error", lua_error_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_error");
	}
	if (!YipHookFunction("lua_next", lua_next_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_next");
	}
	if (!YipHookFunction("lua_concat", lua_concat_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_concat");
	}
	if (!YipHookFunction("lua_getallocf", lua_getallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getallocf");
	}
	if (!YipHookFunction("lua_setallocf", lua_setallocf_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setallocf");
	}
	if (!YipHookFunction("lua_setlevel", lua_setlevel_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlevel");
	}
	if (!YipHookFunction("lua_getstack", lua_getstack_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getstack");
	}
	if (!YipHookFunction("lua_getinfo", lua_getinfo_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getinfo");
	}
	if (!YipHookFunction("lua_getlocal", lua_getlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getlocal");
	}
	if (!YipHookFunction("lua_setlocal", lua_setlocal_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setlocal");
	}
	if (!YipHookFunction("lua_getupvalue", lua_getupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_getupvalue");
	}
	if (!YipHookFunction("lua_setupvalue", lua_setupvalue_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_setupvalue");
	}
	if (!YipHookFunction("lua_sethook", lua_sethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_sethook");
	}
	if (!YipHookFunction("lua_gethook", lua_gethook_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethook");
	}
	if (!YipHookFunction("lua_gethookmask", lua_gethookmask_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookmask");
	}
	if (!YipHookFunction("lua_gethookcount", lua_gethookcount_old, true)) {
		LogW("lua_upgrade: Failed to replace %s", "lua_gethookcount");
	}
}
