/**
 * Registries: register custom code with the game
 */

#ifndef _KATIE_REGISTRY_H_
#define _KATIE_REGISTRY_H_

enum {
	KN_LEVEL_SCRIPT_TICKERS = 0,
	KN_LEVEL_SCRIPT_INITERS,
	KN_SCRIPT_INIT_FUNCS,
	KN_SCRIPT_FRAME_FUNCS,
	KN_SCRIPT_DRAW_FUNCS,
	KN_SCRIPT_DRAW_WORLD_FUNCS,
	KN_SCRIPT_COMMAND_HANDLERS,
	KN_POWERUPS,
	KN_NUM_REGISTRIES,
};

#endif
